version: "3"

services:
  app:
    image: ghcr.io/manyfold3d/manyfold:latest
    ports:
      - 3214:3214
    volumes:
      - /path/to/your/libraries:/libraries
    environment:
      DATABASE_URL: postgresql://manyfold:password@db/manyfold?pool=5
      SECRET_KEY_BASE: a_nice_long_random_string
      REDIS_URL: redis://redis:6379/1
      # RAILS_RELATIVE_URL_ROOT: /manyfold # Sets the root of the app to /manyfold useful for reverse proxies with nginx
      # MULTIUSER: enabled # Uncomment to enable multiuser mode
      # REGISTRATION: enabled # If using multiuser mode, uncomment to let any visitor sign up
    depends_on:
      - db
      - redis
    networks:
      - manyfold
    links:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: manyfold
      POSTGRES_PASSWORD: password
    restart: on-failure
    networks:
      - manyfold

  redis:
    image: redis:7
    restart: on-failure
    networks:
      - manyfold

volumes:
  db_data:


networks:
  manyfold:
