name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    if: github.triggering_actor != 'allcontributors[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - name: Lint Ruby code
        run: bundle exec rake rubocop
      - name: Lint ERB templates
        run: bundle exec erb_lint --lint-all
      - name: Lint Typescript code
        run: yarn run lint:ts
      - name: Check typescript
        run: yarn typecheck
